services:
  app:
    container_name: app
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    tty: true
    networks:
      - sail
  web:
    image: nginx
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./app/dist:/var/www/html
      - ./docker/web/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sail
  
networks:
  sail:
    driver: bridge